miloradowicz/fulfillment-center

api/.prettierrc, api/eslint.config.mjs, api/src/app.module.ts, api/src/config.ts, api/src/main.ts, api/src/mongo/mongo.module.ts, api/test/app.e2e-spec.ts, frontend/.prettierrc, frontend/eslint.config.js, frontend/src/App.tsx, frontend/src/main.tsx, frontend/vite.config.ts
[JE2-20](https://botsmannatashaa.atlassian.net/browse/JE2-20?atlOrigin=eyJpIjoiZTAzYWQyMDAyODliNDEyNWFmNjk2NzE5YmNjYTJhYzEiLCJwIjoiaiJ9)
=> JE2-20. Eslint configured for api and frontend

api/src/clients/create-client.dto.ts, api/src/schemas/client.schema.ts
https://botsmannatashaa.atlassian.net/browse/JE2-8
=> JE2-8 Created client schema & client dto

api/package.json, api/src/clients/clients.controller.ts, api/src/seeder/seed.module.ts, api/src/seeder/seed.ts, api/src/seeder/seeder.service.ts
https://botsmannatashaa.atlassian.net/browse/JE2-11
=> JE2-11. Created cotrollers for clients and test data for them

api/src/app.module.ts, api/src/dto/create-arrival.dto.ts, api/src/schemas/arrival.schema.ts, api/src/seeder/seed.module.ts
https://botsmannatashaa.atlassian.net/browse/JE2-10
=> JE2-10. Created Arrival model and create-DTO for it

frontend/package-lock.json, frontend/package.json, frontend/src/app/hooks.ts, frontend/src/app/store.ts, frontend/src/main.tsx, frontend/src/store/slices/clientSlice.ts, frontend/src/store/thunks/clientThunk.ts, frontend/src/types.d.ts, frontend/src/utils/axiosAPI.ts
https://botsmannatashaa.atlassian.net/browse/JE2-13
1. Configured Redux store.
2. Configured axios.
3. Added interfaces and types in types.d.ts.
4. Created Client Slice.
5. Created Client Thunks.
=> [JE2-13] - create client slice and thunks

api/src/dto/create-order.dto.ts, api/src/dto/create-product.dto.ts, api/src/schemas/order.schema.ts
https://botsmannatashaa.atlassian.net/browse/JE2-25
=> JE2-25 Create order.schema.ts and create-order.dto.ts, prescribed validation for the creation of a new order

api/package-lock.json, api/package.json, api/src/dto/update-product.dto.ts, api/src/main.ts, api/src/products/products.controller.ts, api/src/products/products.service.ts
[JE2-12](https://botsmannatashaa.atlassian.net/browse/JE2-12)
=> JE2-12 Added products service and controller

frontend/src/app/store.ts, frontend/src/store/slices/productSlice.ts, frontend/src/store/thunks/productThunk.ts, frontend/src/types.d.ts
https://botsmannatashaa.atlassian.net/browse/JE2-14
1. Added interfaces and types for products.
4. Created Product Slice.
5. Created Product Thunks.
=> [JE2-14] - create Product slice and thunks

frontend/src/App.tsx, frontend/src/features/clients/components/ClientForm.tsx, frontend/src/main.tsx, frontend/src/utils/axiosAPI.ts
https://botsmannatashaa.atlassian.net/browse/JE2-17
=> JE2-17. Created a form for adding new clients.

frontend/src/app/store.ts, frontend/src/store/slices/arrivalSlice.ts, frontend/src/store/thunks/arrivalThunk.ts, frontend/src/types.d.ts
https://botsmannatashaa.atlassian.net/browse/JE2-16
1. Added interfaces and types for arrivals.
4. Created Arrival Slice.
5. Created Arrival Thunks.
=> [JE2-16] added slice and thunks for arrivals

api/src/app.module.ts, api/src/dto/update-order.dto.ts, api/src/orders/orders.controller.ts, api/src/orders/orders.service.ts
https://botsmannatashaa.atlassian.net/browse/JE2-26
=> JE2-26. Created orders service and controller

api/src/dto/create-order.dto.ts, api/src/schemas/order.schema.ts, api/src/seeder/seeder.service.ts, frontend/src/App.tsx, frontend/src/features/clients/components/OrderForm.tsx, frontend/src/store/slices/orderSlice.ts, frontend/src/store/slices/productSlice.ts, frontend/src/store/thunks/orderThunk.ts, frontend/src/store/thunks/productThunk.ts, frontend/src/types.d.ts
https://botsmannatashaa.atlassian.net/browse/JE2-28
=> Je2-28 (Create form to add )

api/src/dto/create-order.dto.ts, frontend/src/features/clients/components/OrderForm.tsx
https://botsmannatashaa.atlassian.net/browse/JE2-49
=> JE2-49 Add the ability to eliminate product defects, added checks, ad…ded logic for closing buttons when opening modal windows, added loading

api/src/exception-filters/dto-validation-error.filter.ts
https://botsmannatashaa.atlassian.net/browse/JE2-50
=> JE2-50 validation error reformatted

api/src/dto/create-order.dto.ts, frontend/src/App.tsx, frontend/src/features/orders/components/OrderForm.tsx
https://botsmannatashaa.atlassian.net/browse/JE2-53
=> Je2 53 Added error output to onBlur in the order adding form

api/src/dto/create-arrival.dto.ts, api/src/schemas/arrival.schema.ts, frontend/src/features/arrivals/components/ArrivalForm.tsx, frontend/src/features/orders/components/OrderForm.tsx, frontend/src/store/slices/productSlice.ts, frontend/src/store/thunks/productThunk.ts, frontend/src/types.d.ts
https://botsmannatashaa.atlassian.net/browse/JE2-54
=> JE2-54 Added errors when required field looses focus

api/src/schemas/product.schema.ts, frontend/src/app/store.ts, frontend/src/store/slices/userSlice.ts, frontend/src/store/thunks/userThunk.ts, frontend/src/types.d.ts
https://botsmannatashaa.atlassian.net/browse/JE2-36
https://botsmannatashaa.atlassian.net/browse/JE2-45
=> JE2-36 and JE2-45. Fixed logs type in Product schema. Created thunks and slice for User

frontend/package-lock.json, frontend/package.json, frontend/src/features/arrivals/components/ArrivalForm.tsx, frontend/src/index.css, frontend/src/main.tsx, frontend/tailwind.config.ts, frontend/vite.config.ts
https://botsmannatashaa.atlassian.net/browse/JE2-39
=> JE2-39 Added tailwind

frontend/src/App.tsx, frontend/src/components/UI/AppToolbar/AppToolbar.tsx, frontend/src/components/UI/AppToolbar/UserMenu.tsx, frontend/src/components/UI/Layout/Layout.tsx, frontend/src/components/UI/SideBar/SideBar.tsx, frontend/src/features/arrivals/containers/ArrivalPage.tsx, frontend/src/features/clients/containers/ClientPage.tsx, frontend/src/features/orders/containers/OrderPage.tsx, frontend/src/features/products/containers/ProductPage.tsx, frontend/src/features/reports/containers/ReportPage.tsx, frontend/src/features/users/containers/LoginPage.tsx, frontend/src/types.d.ts
https://botsmannatashaa.atlassian.net/browse/JE2-41
=> [JE2-41] Added basic routing to the front

frontend/src/features/arrivals/components/ArrivalForm.tsx, frontend/src/features/orders/components/OrderForm.tsx
https://botsmannatashaa.atlassian.net/browse/JE2-56
=> JE2-56 Fixed errors in Arrival & Order forms

frontend/src/features/arrivals/components/ArrivalForm.tsx
https://botsmannatashaa.atlassian.net/browse/JE2-66
=> JE2-66 Removed navigate, added styles for spinners

api/src/app.module.ts, api/src/controllers/users.controller.ts, api/src/dto/create-user.dto.ts, api/src/main.ts, api/src/modules/arrivals.module.ts, api/src/modules/validators.module.ts, api/src/validators/mongo-document-exists.rule.ts, api/src/validators/mongo-document-exists.ts, frontend/src/App.tsx, frontend/src/components/SelectField/SelectField.tsx, frontend/src/constants.ts, frontend/src/features/users/components/RegistrationForm.tsx, frontend/src/features/users/containers/RegisterPage.tsx, frontend/src/features/users/containers/RegistrationPage.tsx, frontend/src/store/slices/userSlice.ts, frontend/src/store/thunks/userThunk.ts, frontend/src/types.d.ts, frontend/src/utils/helpers.ts
[JE2-46](https://botsmannatashaa.atlassian.net/browse/JE2-46)
=> JE2-46 added user registration form

api/src/controllers/orders.controller.ts, api/src/services/orders.service.ts, frontend/src/features/orders/components/OrdersList.tsx, frontend/src/features/orders/containers/OrderPage.tsx, frontend/src/store/slices/orderSlice.ts, frontend/src/store/thunks/orderThunk.ts, frontend/src/types.d.ts
https://botsmannatashaa.atlassian.net/browse/JE2-59
1. Added interfaces and types for Order with client: Client
2. Added new request /orders?client=1 which fills client in response (order.service & order.controller
3. Added orders with client in order state
4. Created component to display information about all orders
5. The OrderPage now includes a modal window with a form for adding a new order.
=> [JE2-59] A table of all orders has been created

api/src/seeder/seeder.service.ts, frontend/src/features/arrivals/containers/ArrivalPage.tsx, frontend/src/features/orders/components/OrdersList.tsx, frontend/src/features/orders/containers/OrderPage.tsx, frontend/src/features/orders/hooks/useOrderPage.ts, frontend/src/store/thunks/orderThunk.ts, frontend/src/types.d.ts
https://botsmannatashaa.atlassian.net/browse/JE2-91
1. Created custom hook useOrderPage
2. Changed some field in orders table
3. Changed orders table styles
4. Updated fixtures
=> [JE2-91] - refactoring the order table

api/src/app.module.ts, api/src/controllers/arrivals.controller.ts, api/src/controllers/stocks.controller.ts, api/src/dto/create-arrival.dto.ts, api/src/dto/create-stock.dto.ts, api/src/dto/update-stock.dto.ts, api/src/modules/db.module.ts, api/src/modules/stocks.module.ts, api/src/schemas/stock.schema.ts, api/src/seeder/seeder.service.ts, api/src/services/stocks.service.ts
https://botsmannatashaa.atlassian.net/browse/JE2-81
=> JE2-81 Created Stock schema, service, controller & dto for it

api/src/seeder/seeder.service.ts, frontend/src/App.tsx, frontend/src/features/arrivals/hooks/useArrivalDetails.ts, frontend/src/store/slices/arrivalSlice.ts
https://botsmannatashaa.atlassian.net/browse/JE2-94
1. Fixed arrivalSlice
2. Changed error messages in ArrivalDetails
3. Changed seeder
=> [JE2-94] Fixed arrivalSlice

frontend/src/components/UI/Modal/Modal.tsx, frontend/src/features/arrivals/components/ArrivalForm.tsx, frontend/src/features/arrivals/components/ArrivalsDataList.tsx, frontend/src/features/arrivals/containers/ArrivalPage.tsx, frontend/src/features/arrivals/hooks/useArrivalForm.ts, frontend/src/features/arrivals/hooks/useArrivalPage.ts, frontend/src/features/arrivals/hooks/useArrivalsList.ts
https://botsmannatashaa.atlassian.net/browse/JE2-80
=> JE2-80 Updated ArrivalForm to edit arrivals

frontend/src/features/clients/components/ClientForm.tsx, frontend/src/features/clients/components/ClientsDataList.tsx, frontend/src/features/clients/containers/ClientDetail.tsx, frontend/src/features/clients/containers/ClientPage.tsx, frontend/src/features/clients/hooks/useClientForm.ts, frontend/src/features/clients/hooks/useClientPage.ts, frontend/src/hooks/useClientForm.ts
https://botsmannatashaa.atlassian.net/browse/JE2-77
=> JE2-77 Added logic to edit client data

api/src/controllers/orders.controller.ts, api/src/services/orders.service.ts, frontend/src/features/orders/components/OrderForm.tsx, frontend/src/features/orders/components/OrdersList.tsx, frontend/src/features/orders/containers/OrderDetails.tsx, frontend/src/features/orders/containers/OrderPage.tsx, frontend/src/features/orders/hooks/ValidationRulesForBlur.ts, frontend/src/features/orders/hooks/addArrayItemInForm.ts, frontend/src/features/orders/hooks/deleteItem.ts, frontend/src/features/orders/hooks/initialState.ts, frontend/src/features/orders/hooks/useOrderDetails.ts, frontend/src/features/orders/hooks/useOrderForm.ts, frontend/src/features/orders/hooks/useOrderPage.ts, frontend/src/store/slices/orderSlice.ts, frontend/src/store/thunks/orderThunk.ts, frontend/src/types.d.ts
https://botsmannatashaa.atlassian.net/browse/JE2-79
=> Je2 79  Added order editing

frontend/src/App.tsx, frontend/src/app/store.ts, frontend/src/components/UI/SideBar/SideBar.tsx, frontend/src/features/services/components/ServiceForm.tsx, frontend/src/features/services/containers/ServicesPage.tsx, frontend/src/features/services/hooks/useServiceForm.ts, frontend/src/store/slices/serviceSlice.ts, frontend/src/store/thunks/serviceThunk.ts, frontend/src/types.d.ts
https://botsmannatashaa.atlassian.net/browse/JE2-85
=> JE2-85 Implemented form for creating services

api/src/controllers/products.controller.ts, api/src/services/products.service.ts, frontend/src/App.tsx, frontend/src/features/products/components/ProductsDataList.tsx, frontend/src/features/products/containers/ProductDetails.tsx, frontend/src/features/products/containers/ProductPage.tsx, frontend/src/features/products/hooks/useProductActions.ts, frontend/src/store/slices/productSlice.ts, frontend/src/store/thunks/productThunk.ts, frontend/src/types.d.ts
https://botsmannatashaa.atlassian.net/browse/JE2-67
1. Created custom hook useProductActions.
2. Added ProductDetails container.
3. Added product deletion function on all product pages.
4. Added routes.
5. Added request with populate client.
6. Added interfaces.
=> [JE2-67] Create a Product Detail View Card

frontend/src/App.tsx, frontend/src/components/UI/AppToolbar/AppToolbar.tsx, frontend/src/components/UI/AppToolbar/UserMenu.tsx, frontend/src/features/users/components/LoginForm.tsx, frontend/src/features/users/components/RegistrationForm.tsx, frontend/src/features/users/containers/LoginPage.tsx, frontend/src/features/users/containers/RegistrationPage.tsx, frontend/src/features/users/hooks/useLoginForm.ts, frontend/src/store/slices/userSlice.ts, frontend/src/store/thunks/userThunk.ts
https://botsmannatashaa.atlassian.net/browse/JE2-89
=> JE2-89. Created User Login form

frontend/src/features/orders/hooks/addArrayItemInForm.ts, frontend/src/features/orders/hooks/deleteItem.ts, frontend/src/features/orders/hooks/useOrderForm.ts
https://botsmannatashaa.atlassian.net/browse/JE2-96
=> [JE2-96] Fixed typing error in hook order

api/src/services/stocks.service.ts, frontend/src/App.tsx, frontend/src/app/store.ts, frontend/src/components/UI/SideBar/SideBar.tsx, frontend/src/features/arrivals/components/ArrivalDetailsTextItem.tsx, frontend/src/features/arrivals/components/ArrivalForm.tsx, frontend/src/features/arrivals/containers/ArrivalDetails.tsx, frontend/src/features/arrivals/hooks/useArrivalDetails.ts, frontend/src/features/arrivals/hooks/useArrivalForm.ts, frontend/src/features/arrivals/hooks/useArrivalPage.ts, frontend/src/features/stocks/components/StockCard.tsx, frontend/src/features/stocks/components/StockForm.tsx, frontend/src/features/stocks/containers/StockDetails.tsx, frontend/src/features/stocks/containers/StockPage.tsx, frontend/src/features/stocks/hooks/useStockCard.ts, frontend/src/features/stocks/hooks/useStockDetails.ts, frontend/src/features/stocks/hooks/useStockForm.ts, frontend/src/features/stocks/hooks/useStockPage.ts, frontend/src/features/stocks/state/stockState.ts, frontend/src/store/slices/stocksSlice.ts, frontend/src/store/thunks/stocksThunk.ts, frontend/src/types.d.ts, frontend/src/utils/getProductName.ts
https://botsmannatashaa.atlassian.net/browse/JE2-82
=> JE2-82 Created everything related with Stock

frontend/src/features/stocks/hooks/useStockForm.ts
https://botsmannatashaa.atlassian.net/browse/JE2-98
=> [JE2-98] Updated handleBlur

api/src/app.module.ts, api/src/controllers/logs.controller.ts, api/src/controllers/users.controller.ts, api/src/decorators/roles.decorator.ts, api/src/decorators/user.param-decorator.ts, api/src/guards/roles.guard.ts, api/src/guards/token-auth.guard.ts, api/src/main.ts, api/src/modules/arrivals.module.ts, api/src/modules/auth.module.ts, api/src/modules/clients.module.ts, api/src/modules/logs.module.ts, api/src/modules/orders.module.ts, api/src/modules/products.module.ts, api/src/modules/services.module.ts, api/src/modules/stocks.module.ts, api/src/modules/tasks.module.ts, api/src/modules/users.module.ts, api/src/modules/validators.module.ts, api/src/schemas/user.schema.ts, api/src/services/logs.service.ts, api/src/services/roles.service.ts, api/src/services/token-auth.service.ts, api/src/types.d.ts
[JE2-99](https://botsmannatashaa.atlassian.net/browse/JE2-99)
=> JE2-99 resolved merge conflicts and restored functionality

api/src/dto/create-arrival.dto.ts, api/src/dto/create-order.dto.ts, frontend/src/features/arrivals/components/ArrivalForm.tsx, frontend/src/features/arrivals/hooks/useArrivalForm.ts, frontend/src/features/arrivals/hooks/useArrivalPage.ts, frontend/src/features/arrivals/state/arrivalState.ts, frontend/src/features/orders/components/OrderForm.tsx, frontend/src/features/orders/hooks/addArrayItemInForm.ts, frontend/src/features/orders/hooks/useOrderForm.ts, frontend/src/features/orders/hooks/useOrderPage.ts, frontend/src/main.tsx, frontend/src/store/slices/arrivalSlice.ts, frontend/src/store/slices/orderSlice.ts, frontend/src/store/thunks/arrivalThunk.ts, frontend/src/store/thunks/orderThunk.ts, frontend/src/types.d.ts
https://botsmannatashaa.atlassian.net/browse/JE2-116
=> [JE2-116] Added the status field to the forms for creating/editing arrivals and orders, implemented error catching, and adjusted the error state reset

api/src/controllers/arrivals.controller.ts, api/src/controllers/clients.controller.ts, api/src/controllers/orders.controller.ts, api/src/controllers/products.controller.ts, api/src/controllers/services.controller.ts, api/src/controllers/stocks.controller.ts, api/src/controllers/tasks.controller.ts, api/src/controllers/users.controller.ts, api/src/schemas/arrival.schema.ts, api/src/schemas/client.schema.ts, api/src/schemas/order.schema.ts, api/src/schemas/product.schema.ts, api/src/schemas/service.schema.ts, api/src/schemas/stock.schema.ts, api/src/schemas/task.schema.ts, api/src/schemas/user.schema.ts, api/src/services/arrivals.service.ts, api/src/services/clients.service.ts, api/src/services/orders.service.ts, api/src/services/products.service.ts, api/src/services/services.service.ts, api/src/services/stocks.service.ts, api/src/services/tasks.service.ts, api/src/services/user.service.ts
[JE2-102](https://botsmannatashaa.atlassian.net/browse/JE2-102)
=> JE2-102 added archiving feature

frontend/src/features/products/components/ProductForm.tsx, frontend/src/features/products/components/ProductsDataList.tsx, frontend/src/features/products/containers/ProductDetails.tsx, frontend/src/features/products/containers/ProductPage.tsx, frontend/src/features/products/hooks/useProductActions.ts, frontend/src/features/products/hooks/useProductForm.ts, frontend/src/hooks/useProductForm.ts, frontend/src/store/slices/productSlice.ts, frontend/src/store/thunks/productThunk.ts
https://botsmannatashaa.atlassian.net/browse/JE2-130
1. Added products update on ProductPage after successful creation of a new product.
2. Added createAndUpdateError to the product slice to handle errors when creating and updating products.
3. Added error handling from the backend. Errors are now displayed in fields.
4. "Продукт" changed to "товар"
=> JE2-130 Product form refactoring. Backend errors handling

api/src/dto/create-client.dto.ts
[JE2-127](https://botsmannatashaa.atlassian.net/browse/JE2-127)
=> JE2-127 bugfix for JE2-74

frontend/src/features/stocks/components/StockForm.tsx, frontend/src/features/stocks/hooks/useStockForm.ts, frontend/src/features/stocks/state/stockState.ts, frontend/src/store/thunks/stocksThunk.ts, frontend/src/types.d.ts
https://botsmannatashaa.atlassian.net/browse/JE2-104
=> [JE2-104] Deleted "add product" field from stock form

frontend/src/features/arrivals/components/ArrivalsDataList.tsx, frontend/src/features/arrivals/components/StatusArrivalCell.tsx, frontend/src/features/orders/components/OrderStatusCell.tsx, frontend/src/features/orders/components/OrdersList.tsx, frontend/src/features/orders/components/StatusOrderCell.tsx
https://botsmannatashaa.atlassian.net/browse/JE2-108
=> [JE2-108] Added menu for switching statuses

api/src/dto/create-client.dto.ts, api/src/dto/create-counterparty.dto.ts, api/src/dto/update-counterparty.dto.ts, api/src/schemas/counterparty.schema.ts
https://botsmannatashaa.atlassian.net/browse/JE2-117
=> [JE2-117] Created counterparty model

api/src/dto/create-arrival.dto.ts, api/src/schemas/arrival.schema.ts, api/src/services/arrivals.service.ts, frontend/src/features/arrivals/components/ArrivalForm.tsx, frontend/src/features/arrivals/components/ArrivalsDataList.tsx, frontend/src/features/arrivals/components/StatusArrivalCell.tsx, frontend/src/features/arrivals/containers/ArrivalDetails.tsx, frontend/src/features/arrivals/hooks/useArrivalForm.ts, frontend/src/features/arrivals/hooks/useArrivalPage.ts, frontend/src/features/arrivals/state/arrivalState.ts, frontend/src/features/orders/components/OrderForm.tsx, frontend/src/features/orders/hooks/useOrderForm.ts, frontend/src/features/stocks/containers/StockDetails.tsx, frontend/src/features/stocks/containers/StockPage.tsx, frontend/src/features/stocks/hooks/useStockDetails.ts, frontend/src/features/stocks/hooks/useStockPage.ts, frontend/src/store/slices/stocksSlice.ts, frontend/src/types.d.ts, frontend/src/utils/getAvailableItems.ts, frontend/src/utils/getItemNameById.ts
https://botsmannatashaa.atlassian.net/browse/JE2-125
=> [JE2-125] Updated ArrivalForm by adding Stock in it

frontend/src/features/tasks/components/TaskBoard.tsx, frontend/src/features/tasks/components/TaskCard.tsx, frontend/src/features/tasks/components/TaskLine.tsx, frontend/src/features/tasks/hooks/onDragEnd.ts, frontend/src/features/tasks/hooks/useTaskBoard.ts, frontend/src/store/slices/taskSlice.ts, frontend/src/store/thunks/tasksThunk.ts
https://botsmannatashaa.atlassian.net/browse/JE2-111
=> Je2 111 Added a menu for editing and deleting in task cards

api/src/app.module.ts, api/src/controllers/counterparties.controller.ts, api/src/modules/counterparties.module.ts, api/src/modules/db.module.ts, api/src/seeder/seeder.service.ts, api/src/services/counterparties.service.ts
https://botsmannatashaa.atlassian.net/browse/JE2-119
=> JE2-119. Created Counterparties service, controller and fixtures

frontend/src/app/store.ts, frontend/src/store/slices/counterpartySlices.ts, frontend/src/store/thunks/counterpartyThunk.ts, frontend/src/types.d.ts
https://botsmannatashaa.atlassian.net/browse/JE2-118
=> JE2-118 Created thunks and slices for counterparties

api/src/modules/arrivals.module.ts, api/src/modules/db.module.ts, api/src/modules/orders.module.ts, api/src/schemas/arrival.schema.ts, api/src/schemas/counter.schema.ts, api/src/schemas/order.schema.ts, api/src/seeder/seeder.service.ts, api/src/services/arrivals.service.ts, api/src/services/counter.service.ts, api/src/services/orders.service.ts
https://botsmannatashaa.atlassian.net/browse/JE2-109
1. Created Counter for auto-incrementation of delivery and order numbers
2. Added fields orderNumber and arrivalNumber in schemas.
3. Created the addition of the delivery number and order number when creating.
4. Updated fixtures.
=> JE2-109 Add numbering for deliveries and orders

frontend/src/store/slices/counterpartySlices.ts, frontend/src/store/thunks/counterpartyThunk.ts
https://botsmannatashaa.atlassian.net/browse/JE2-134
=> JE2-134. Fixed Counterparty slice and thunks

api/src/dto/create-task.dto.ts, api/src/schemas/task.schema.ts, api/src/seeder/seeder.service.ts
https://botsmannatashaa.atlassian.net/browse/JE2-115
1. Added fields type, associated_order and associated_arrival in schema and dto.
2. Updated fixtures.
=> [JE2-115] Updated fields in Task schema

api/src/dto/create-product.dto.ts, api/src/services/products.service.ts, frontend/src/features/products/hooks/useProductActions.ts, frontend/src/features/products/hooks/useProductForm.ts, frontend/src/store/slices/productSlice.ts
https://botsmannatashaa.atlassian.net/browse/JE2-131
1. The uniqueness check in the productDto has been removed.
2. A uniqueness check for the article and barcode has been added in the product service during creation and update.
=> [JE2-131] The uniqueness validation for the product has been changed.

api/src/dto/create-arrival.dto.ts, api/src/schemas/arrival.schema.ts, api/src/seeder/seeder.service.ts, api/src/services/arrivals.service.ts, frontend/src/features/arrivals/components/ArrivalForm.tsx, frontend/src/features/arrivals/components/ArrivalsDataList.tsx, frontend/src/features/arrivals/components/StatusArrivalCell.tsx, frontend/src/features/arrivals/containers/ArrivalDetails.tsx, frontend/src/features/arrivals/hooks/useArrivalForm.ts, frontend/src/features/arrivals/state/arrivalState.ts, frontend/src/features/orders/components/OrderForm.tsx, frontend/src/features/orders/components/OrdersList.tsx, frontend/src/types.d.ts, frontend/src/utils/getItemNameById.ts
https://botsmannatashaa.atlassian.net/browse/JE2-113
=> [JE2-113] Updated Arrival with shipping_agent & pickup_location fields

api/src/modules/clients.module.ts, api/src/modules/db.module.ts, api/src/modules/products.module.ts, api/src/schemas/client.schema.ts, api/src/schemas/user.schema.ts, api/src/seeder/seeder.service.ts, api/src/services/clients.service.ts, api/src/services/products.service.ts
[JE2-112](https://botsmannatashaa.atlassian.net/browse/JE2-112)
=> Je2 112 cascade archive/delete with basic checks

frontend/src/store/slices/arrivalSlice.ts, frontend/src/store/slices/clientSlice.ts, frontend/src/store/slices/orderSlice.ts, frontend/src/store/slices/productSlice.ts, frontend/src/store/slices/serviceSlice.ts, frontend/src/store/slices/stocksSlice.ts, frontend/src/store/slices/userSlice.ts, frontend/src/store/thunks/arrivalThunk.ts, frontend/src/store/thunks/clientThunk.ts, frontend/src/store/thunks/orderThunk.ts, frontend/src/store/thunks/productThunk.ts, frontend/src/store/thunks/serviceThunk.ts, frontend/src/store/thunks/stocksThunk.ts, frontend/src/store/thunks/userThunk.ts
[JE2-103](https://botsmannatashaa.atlassian.net/browse/JE2-103)
=> JE2-103 archivation thunks added

api/src/app.module.ts, api/src/controllers/service-categories.controller.ts, api/src/dto/create-service-category.dto.ts, api/src/dto/create-service.dto.ts, api/src/dto/update-service-category.dto.ts, api/src/modules/db.module.ts, api/src/modules/service-category.module.ts, api/src/schemas/service-category.schema.ts, api/src/schemas/service.schema.ts, api/src/seeder/seeder.service.ts, api/src/services/service-categories.service.ts, api/src/services/services.service.ts
https://botsmannatashaa.atlassian.net/browse/JE2-123
=> [JE2-123] Created ServiceCategory schema, dto, controller & service

api/src/seeder/seeder.service.ts, api/src/services/clients.service.ts, frontend/src/features/clients/containers/ClientDetail.tsx, frontend/src/features/clients/hooks/useClientsList.ts
https://botsmannatashaa.atlassian.net/browse/JE2-129
=> [JE2-129] Fixed ClientDetail toast error

frontend/src/App.tsx, frontend/src/features/counterparties/components/CounterpartyForm.tsx, frontend/src/features/counterparties/hooks/useCounterpartyForm.ts, frontend/src/features/counterparties/state/counterpartyState.ts, frontend/src/store/slices/counterpartySlices.ts, frontend/src/types.d.ts
[JE2-120](https://botsmannatashaa.atlassian.net/browse/JE2-120)
=> [JE2-120] Created form for creating new counterparties.

api/src/dto/create-arrival.dto.ts, api/src/dto/create-order.dto.ts, api/src/schemas/arrival.schema.ts, api/src/schemas/order.schema.ts, frontend/src/features/arrivals/hooks/useArrivalForm.ts, frontend/src/features/orders/components/OrderForm.tsx, frontend/src/features/orders/components/OrdersList.tsx, frontend/src/features/orders/containers/OrderDetails.tsx, frontend/src/features/orders/hooks/initialState.ts, frontend/src/features/orders/hooks/useOrderForm.ts, frontend/src/types.d.ts
https://botsmannatashaa.atlassian.net/browse/JE2-106
=> [JE2-106] Made delivered_at field in Order optional

frontend/src/App.tsx, frontend/src/components/UI/SideBar/SideBar.tsx, frontend/src/features/counterparties/components/CounterpartiesDataList.tsx, frontend/src/features/counterparties/containers/CounterpartiesPage.tsx, frontend/src/features/counterparties/hooks/useCounterpartiesList.ts, frontend/src/features/counterparties/hooks/useCounterpartyForm.ts, frontend/src/features/counterparties/hooks/useCounterpartyPage.ts
[JE2-121](https://botsmannatashaa.atlassian.net/browse/JE2-121)
=> JE2-121 Implemented getting all counterparties and output in the table.

api/src/services/counterparties.service.ts, frontend/src/features/counterparties/hooks/useCounterpartyForm.ts
[JE2-142](https://botsmannatashaa.atlassian.net/browse/JE2-142)
=> JE2-142 Implemented name uniqueness check for counterparties

frontend/src/features/tasks/components/TaskBoard.tsx, frontend/src/features/tasks/components/TaskCard.tsx, frontend/src/features/tasks/components/TaskCardSceleton.tsx, frontend/src/features/tasks/components/TaskLine.tsx, frontend/src/features/tasks/components/UserList.tsx, frontend/src/features/tasks/hooks/TypesProps.d.ts, frontend/src/features/tasks/hooks/onDragEnd.ts, frontend/src/features/tasks/hooks/useTaskBoard.ts, frontend/src/types.d.ts
https://botsmannatashaa.atlassian.net/browse/JE2-146
=> [JE2-146] Cleaned up the dnd task page from bugs, added creation and update dates to the task output

api/src/dto/create-task.dto.ts, api/src/schemas/task.schema.ts, frontend/src/features/tasks/components/TaskForm.tsx, frontend/src/features/tasks/hooks/useTaskForm.ts, frontend/src/features/tasks/state/taskState.ts, frontend/src/types.d.ts
https://botsmannatashaa.atlassian.net/browse/JE2-110
TaskForm with the function of adding new tasks has been created
=> [JE2-110] Added task form

frontend/src/Layout/Layout.tsx, frontend/src/components/UI/AppToolbar/AppToolbar.tsx, frontend/src/features/orders/components/StatusOrderCell.tsx, frontend/src/features/tasks/components/StatusCell.tsx, frontend/src/features/tasks/components/TaskCard.tsx, frontend/src/features/tasks/hooks/TypesProps.d.ts, frontend/src/types.d.ts
https://botsmannatashaa.atlassian.net/browse/JE2-156
=> [JE2-156] Adapted dnd for use on mobile devices with touch

api/src/controllers/arrivals.controller.ts, api/src/controllers/clients.controller.ts, api/src/controllers/counterparties.controller.ts, api/src/controllers/orders.controller.ts, api/src/controllers/products.controller.ts, api/src/controllers/service-categories.controller.ts, api/src/controllers/services.controller.ts, api/src/controllers/stocks.controller.ts, api/src/controllers/tasks.controller.ts, api/src/controllers/users.controller.ts, api/src/services/arrivals.service.ts, api/src/services/clients.service.ts, api/src/services/counterparties.service.ts, api/src/services/orders.service.ts, api/src/services/products.service.ts, api/src/services/service-categories.service.ts, api/src/services/services.service.ts, api/src/services/stocks.service.ts, api/src/services/tasks.service.ts, api/src/services/user.service.ts
https://botsmannatashaa.atlassian.net/browse/JE2-139
=> JE2-139. Added endpoints to every entity for GET requests to all archived documents and archived documents by id

api/src/controllers/arrivals.controller.ts, api/src/controllers/products.controller.ts, api/src/dto/create-arrival.dto.ts, api/src/dto/create-product.dto.ts, api/src/modules/arrivals.module.ts, api/src/modules/products.module.ts, api/src/schemas/arrival.schema.ts, api/src/schemas/product.schema.ts, api/src/services/arrivals.service.ts, api/src/services/products.service.ts, frontend/src/features/arrivals/components/ArrivalForm.tsx, frontend/src/features/arrivals/containers/ArrivalDetails.tsx, frontend/src/features/arrivals/hooks/useArrivalForm.ts, frontend/src/features/arrivals/state/arrivalState.ts, frontend/src/features/products/components/ProductForm.tsx, frontend/src/features/products/hooks/useProductForm.ts, frontend/src/store/thunks/arrivalThunk.ts, frontend/src/store/thunks/productThunk.ts, frontend/src/types.d.ts, frontend/src/utils/createArrivalFormData.ts
https://botsmannatashaa.atlassian.net/browse/JE2-147
=> [JE2-147] Updated Arrival by adding there "documents" field

api/src/seeder/seeder.service.ts, api/src/services/tasks.service.ts, frontend/src/components/UI/CustomButton/CustomButton.tsx, frontend/src/components/UI/CustomTitle/CustomTitle.tsx, frontend/src/features/arrivals/containers/ArrivalPage.tsx, frontend/src/features/clients/containers/ClientPage.tsx, frontend/src/features/counterparties/containers/CounterpartiesPage.tsx, frontend/src/features/orders/containers/OrderPage.tsx, frontend/src/features/products/containers/ProductPage.tsx, frontend/src/features/services/containers/ServicesPage.tsx, frontend/src/features/stocks/containers/StockPage.tsx, frontend/src/features/tasks/components/StatusCell.tsx, frontend/src/features/tasks/components/TaskBoard.tsx, frontend/src/features/tasks/components/TaskCard.tsx, frontend/src/features/tasks/components/TaskForm.tsx, frontend/src/features/tasks/components/UserList.tsx, frontend/src/features/tasks/hooks/useTaskBoard.ts, frontend/src/features/tasks/hooks/useTaskForm.ts, frontend/src/types.d.ts
https://botsmannatashaa.atlassian.net/browse/JE2-150
=> [JE2-150] Moved the add buttons and headings to a separate component, connected the task creation form, changed the task display

frontend/src/components/UI/Modal/ConfirmationModal.tsx, frontend/src/features/arrivals/components/ArrivalsDataList.tsx, frontend/src/features/arrivals/containers/ArrivalDetails.tsx, frontend/src/features/arrivals/hooks/useArrivalDetails.ts, frontend/src/features/arrivals/hooks/useArrivalsList.ts, frontend/src/features/clients/components/ClientsDataList.tsx, frontend/src/features/clients/containers/ClientDetail.tsx, frontend/src/features/clients/hooks/useClientsList.ts, frontend/src/features/counterparties/components/CounterpartiesDataList.tsx, frontend/src/features/counterparties/hooks/useCounterpartiesList.ts, frontend/src/features/orders/components/OrdersList.tsx, frontend/src/features/orders/containers/OrderDetails.tsx, frontend/src/features/orders/hooks/useOrderPage.ts, frontend/src/features/products/components/ProductsDataList.tsx, frontend/src/features/products/containers/ProductDetails.tsx, frontend/src/features/products/hooks/useProductActions.ts, frontend/src/features/stocks/containers/StockDetails.tsx, frontend/src/features/stocks/hooks/useStockDetails.ts, frontend/src/features/tasks/components/TaskCard.tsx
https://botsmannatashaa.atlassian.net/browse/JE2-151
=> JE2-151. Created a separate modal component for deletion or archiving confirmation

frontend/index.html, frontend/package.json, frontend/src/App.tsx, frontend/src/components/Tables/DefectsTable.tsx, frontend/src/components/Tables/LogsTable.tsx, frontend/src/components/Tables/ProductsTable.tsx, frontend/src/constants.ts, frontend/src/features/arrivals/components/StatusArrivalCell.tsx, frontend/src/features/arrivals/containers/ArrivalDetails.tsx, frontend/src/features/arrivals/hooks/useArrivalDetails.ts, frontend/src/features/orders/containers/OrderDetails.tsx, frontend/src/features/orders/hooks/useOrderDetails.ts, frontend/src/main.tsx, frontend/src/types.d.ts, frontend/src/utils/getOrderStatusColor.ts
https://botsmannatashaa.atlassian.net/browse/JE2-141
Fixed branch with order and arrival details
=> JE2-141 order and arrival detail pages

frontend/src/features/reports/components/TaskCountChart.tsx
https://botsmannatashaa.atlassian.net/browse/JE2-169
=> [JE2-169] Changed graphic styles so dates are not cut off

api/src/controllers/arrivals.controller.ts, api/src/modules/file-upload.module.ts, api/src/services/clients.service.ts, api/src/services/counterparties.service.ts, api/src/services/orders.service.ts, api/src/utils/uploadFiles.ts, frontend/src/constants.ts, frontend/src/features/arrivals/components/ArrivalForm.tsx, frontend/src/features/arrivals/hooks/useArrivalForm.ts, frontend/src/features/arrivals/state/arrivalState.ts, frontend/src/features/counterparties/components/CounterpartiesDataList.tsx, frontend/src/features/orders/components/OrderForm.tsx, frontend/src/features/orders/hooks/ValidationRulesForBlur.ts, frontend/src/features/orders/hooks/initialState.ts, frontend/src/features/orders/hooks/useOrderForm.ts, frontend/src/features/products/hooks/useProductForm.ts, frontend/src/features/tasks/hooks/useTaskForm.ts, frontend/src/features/users/hooks/useRegistrationForm.ts, frontend/src/messages.ts, frontend/src/store/thunks/arrivalThunk.ts, frontend/src/types.d.ts, frontend/src/utils/createArrivalFormData.ts
https://botsmannatashaa.atlassian.net/browse/JE2-154
=> [JE2-154] FE/BE refactor

api/src/services/tasks.service.ts, frontend/src/features/tasks/components/TaskCard.tsx, frontend/src/features/tasks/components/TaskForm.tsx, frontend/src/features/tasks/hooks/useTaskForm.ts, frontend/src/features/tasks/state/taskState.ts, frontend/src/types.d.ts
https://botsmannatashaa.atlassian.net/browse/JE2-157
1. Added task update functionality in the task form.
2. Enabled opening the modal window with the task form in the TaskCard component.
3. Removed the task status field from the form.
4. Updated task modification logic in the task service: now, the previously associated entity is removed if the task type is changed.
=> [JE2-157]  Added task editing

frontend/src/components/UI/Modal/Modal.tsx, frontend/src/features/clients/components/ClientForm.tsx, frontend/src/features/counterparties/components/CounterpartyForm.tsx, frontend/src/features/orders/components/OrderForm.tsx, frontend/src/features/products/components/ProductForm.tsx, frontend/src/features/services/components/ServiceForm.tsx, frontend/src/features/stocks/components/StockForm.tsx, frontend/src/features/tasks/components/TaskForm.tsx
https://botsmannatashaa.atlassian.net/browse/JE2-107
=> JE2-107. Changed the Modal component to adjust its fields width

api/src/modules/tasks.module.ts, api/src/schemas/task.schema.ts, api/src/seeder/seeder.service.ts, api/src/services/tasks.service.ts, frontend/src/features/tasks/components/TaskCard.tsx, frontend/src/types.d.ts
https://botsmannatashaa.atlassian.net/browse/JE2-172
1. Added taskNumber to the Task schema
2. Task number is assigned automatically when creating a task
3. Updated fixtures
4. Displayed task number in TaskCard
5. Updated interfaces (frontend)
=> [JE2-172] added task number

api/src/controllers/orders.controller.ts, api/src/dto/create-order.dto.ts, api/src/modules/orders.module.ts, api/src/schemas/order.schema.ts, api/src/services/orders.service.ts, api/src/utils/uploadFiles.ts, frontend/src/features/orders/components/OrderForm.tsx, frontend/src/features/orders/containers/OrderDetails.tsx, frontend/src/features/orders/hooks/initialState.ts, frontend/src/features/orders/hooks/useOrderDetails.ts, frontend/src/features/orders/hooks/useOrderForm.ts, frontend/src/store/thunks/arrivalThunk.ts, frontend/src/store/thunks/orderThunk.ts, frontend/src/types.d.ts, frontend/src/utils/createArrivalAndOrderFormData.ts
https://botsmannatashaa.atlassian.net/browse/JE2-162
=> [JE2-162] Added the ability to add documents to an order

frontend/src/features/tasks/components/TaskCard.tsx, frontend/src/features/tasks/components/TaskForm.tsx
https://botsmannatashaa.atlassian.net/browse/JE2-181
1. Deleted  e.preventDefault() in TaskCard
2. Deleted onClick in submit button (TaskForm)
=> JE2-181 Fixed task form submit in task card

api/src/dto/create-order.dto.ts, api/src/schemas/order.schema.ts, api/src/seeder/seeder.service.ts, api/src/services/orders.service.ts, frontend/src/features/arrivals/components/ArrivalForm.tsx, frontend/src/features/orders/components/OrderForm.tsx, frontend/src/features/orders/components/OrdersList.tsx, frontend/src/features/orders/containers/OrderDetails.tsx, frontend/src/features/orders/hooks/initialState.ts, frontend/src/features/orders/hooks/useOrderForm.ts, frontend/src/store/thunks/orderThunk.ts, frontend/src/types.d.ts
https://botsmannatashaa.atlassian.net/browse/JE2-175
=> [JE2-175] Added stock into Order

frontend/src/features/users/components/LoginForm.tsx, frontend/src/features/users/components/RegistrationForm.tsx, frontend/src/features/users/hooks/useLoginForm.ts, frontend/src/features/users/hooks/useRegistrationForm.ts, frontend/src/store/slices/userSlice.ts, frontend/src/store/thunks/userThunk.ts
https://botsmannatashaa.atlassian.net/browse/JE2-161
=> JE2-161. Login and Registration forms' bug fixes and styling

frontend/src/features/tasks/components/TaskLine.tsx, frontend/src/features/tasks/utils/statusStyle.ts
https://botsmannatashaa.atlassian.net/browse/JE2-171
1. Added display of the number of tasks in columns
2. Heading styles in task columns by status have been changed.
=> [JE2-171] Added task count display

api/src/dto/create-arrival.dto.ts, api/src/schemas/arrival.schema.ts, api/src/seeder/seeder.service.ts, api/src/services/arrivals.service.ts, frontend/src/constants.ts, frontend/src/features/arrivals/components/ArrivalForm.tsx, frontend/src/features/arrivals/components/ItemsList.tsx, frontend/src/features/arrivals/hooks/useArrivalForm.ts, frontend/src/features/arrivals/state/arrivalState.ts, frontend/src/features/arrivals/utils/arrivalTypes.ts, frontend/src/features/clients/components/ClientsDataList.tsx, frontend/src/features/orders/components/OrderForm.tsx, frontend/src/features/orders/components/StatusOrderCell.tsx, frontend/src/features/products/components/ProductsDataList.tsx, frontend/src/features/products/containers/ProductPage.tsx, frontend/src/features/tasks/components/TaskForm.tsx, frontend/src/messages.ts, frontend/src/store/thunks/stocksThunk.ts, frontend/src/types.d.ts, frontend/src/utils/getArrayItemName.ts, frontend/src/utils/getAutocompleteItemName.ts, frontend/src/utils/getProductName.ts
https://botsmannatashaa.atlassian.net/browse/JE2-177
=> [JE2-177] Added services into Arrival

api/src/services/report.service.ts, api/src/types.d.ts, frontend/src/features/reports/components/ButtonDataRange.tsx, frontend/src/features/reports/components/DateRangePicker.tsx, frontend/src/features/reports/components/TaskCountChart.tsx, frontend/src/features/reports/components/TaskDropdown.tsx, frontend/src/features/reports/components/TaskReport.tsx, frontend/src/features/reports/components/TaskReportTable.tsx, frontend/src/features/reports/components/TaskStateForReport.tsx, frontend/src/features/reports/containers/ReportPage.tsx, frontend/src/features/reports/hooks/usePesponsiveState.ts, frontend/src/features/reports/hooks/useTaskCountAreaChart.ts, frontend/src/features/reports/hooks/useTaskRangePicker.ts, frontend/src/features/reports/hooks/useTaskStateForReport.ts, frontend/src/features/reports/hooks/useWndowWidth.ts, frontend/src/features/reports/utils/CustomTabPanel.tsx, frontend/src/features/reports/utils/UseIMobile.ts, frontend/src/features/reports/utils/taskReportConstants.ts, frontend/src/features/tasks/components/UserList.tsx, frontend/src/types.d.ts
https://botsmannatashaa.atlassian.net/browse/JE2-174
=> Je2 174 Added a dropdown with links to tasks to the task report, adapted for mobile screens

frontend/src/App.tsx
[JE2-193](https://botsmannatashaa.atlassian.net/browse/JE2-193)
=> JE2-193 bugfix for JE2-114

frontend/src/store/slices/authSlice.ts
https://botsmannatashaa.atlassian.net/browse/JE2-194
=> JE2-194. Bug fix when Login fields get blocked after receiving an error

api/package.json, api/test/client.service.spec.ts, frontend/jest.config.ts, frontend/jest.setup.ts, frontend/package-lock.json, frontend/package.json, frontend/src/tests/ClientForm.test.tsx, frontend/src/tests/useClientForm.test.tsx, frontend/tsconfig.test.json
https://botsmannatashaa.atlassian.net/browse/JE2-195
=> Test Add test for ClientService and ClientForm 

api/src/dto/create-invoice.dto.ts, api/src/dto/create-service.dto.ts, api/src/schemas/invoice.schema.ts, api/src/schemas/service.schema.ts, api/src/seeder/seeder.service.ts, frontend/src/features/services/components/ServiceForm.tsx, frontend/src/features/services/hooks/useServiceForm.ts, frontend/src/types.d.ts
https://botsmannatashaa.atlassian.net/browse/JE2-204
=> JE2-204. Added type field to Service

frontend/src/components/AppToolbar/AppToolbar.tsx, frontend/src/features/products/components/ProductsDataList.tsx
https://botsmannatashaa.atlassian.net/browse/JE2-214
=> [JE2-214] Updated Products table styles

frontend/package-lock.json, frontend/package.json, frontend/src/components/DataTable/DataTableColumnHeader/DataTableColumnHeader.tsx, frontend/src/components/DataTable/TableActionsMenu/TableActionsMenu.tsx, frontend/src/components/ui/badge.tsx, frontend/src/components/ui/tooltip.tsx, frontend/src/features/arrivals/components/ArrivalsDataList.tsx, frontend/src/features/arrivals/components/StatusArrivalCell.tsx, frontend/src/features/arrivals/hooks/useArrivalForm.ts, frontend/src/features/arrivals/hooks/useArrivalsList.ts
https://botsmannatashaa.atlassian.net/browse/JE2-215
=> [JE2-215] Updated ArrivalsDataList & StatusArrivalCell styles

frontend/src/components/CommonStatusCell/CommonStatusCell.tsx, frontend/src/features/arrivals/components/StatusArrivalCell.tsx, frontend/src/features/orders/components/OrdersList.tsx, frontend/src/features/orders/components/StatusOrderCell.tsx, frontend/src/utils/capitalizeFirstLetter.ts, frontend/src/utils/createArrivalAndOrderFormData.ts, frontend/src/utils/handleErrorToast.ts
https://botsmannatashaa.atlassian.net/browse/JE2-216
=> [JE2-216] Updated OrdersList styles

frontend/src/features/counterparties/components/CounterpartiesDataList.tsx, frontend/src/features/counterparties/hooks/useCounterpartiesList.ts
https://botsmannatashaa.atlassian.net/browse/JE2-217
=> [JE2-217] Updated counterparty table styles

frontend/src/features/arrivals/containers/ArrivalPage.tsx, frontend/src/features/arrivals/hooks/useArrivalPage.ts, frontend/src/features/arrivals/state/arrivalState.ts, frontend/src/features/orders/hooks/useOrderPage.ts
[JE2-202](https://botsmannatashaa.atlassian.net/browse/JE2-202)
=> JE2-202 Added button to open ProductForm in ArrivaPage.

api/src/dto/create-invoice.dto.ts, api/src/schemas/invoice.schema.ts, api/src/seeder/seeder.service.ts, api/src/services/invoices.service.ts, package-lock.json
https://botsmannatashaa.atlassian.net/browse/JE2-240
Fields paid_amount and discount have been added to the invoice schema.
The fields totalAmount and status are now optional
Seeder: added invoice counter update
calculateTotalAmount has been updated to include discount calculation for internal services
Added determineStatus function for automatic payment status updates
=> JE2-240 invoice refactor

frontend/package-lock.json, frontend/package.json, frontend/src/components/ui/button.tsx, frontend/src/features/clients/components/ClientForm.tsx, frontend/src/features/clients/hooks/useClientForm.ts, frontend/src/features/products/components/ProductForm.tsx
https://botsmannatashaa.atlassian.net/browse/JE2-219
=> [JE2-219] Changed ClientForm styles to shadcn

frontend/src/features/clients/components/ClientForm.tsx, frontend/src/features/counterparties/components/CounterpartyForm.tsx, frontend/src/features/products/components/ProductForm.tsx
https://botsmannatashaa.atlassian.net/browse/JE2-226
=> [JE2-226] Updated CounterpartyForm styles

frontend/src/features/arrivals/containers/ArrivalDetails.tsx, frontend/src/features/orders/containers/OrderDetails.tsx
https://botsmannatashaa.atlassian.net/browse/JE2-257
=> [JE2-257] On the arrival details page, I corrected the path of the link for downloading the file

api/src/dto/create-service.dto.ts, api/src/dto/create-stock.dto.ts, frontend/src/features/clients/components/ClientForm.tsx, frontend/src/features/stocks/components/StockForm.tsx, frontend/src/features/stocks/hooks/useStockForm.ts, frontend/src/store/slices/stocksSlice.ts, frontend/src/store/thunks/stocksThunk.ts, frontend/src/types.d.ts
https://botsmannatashaa.atlassian.net/browse/JE2-225
=> [JE2-225] Updated StockForm styles

api/src/controllers/users.controller.ts, api/src/seeder/seeder.service.ts, api/src/services/user.service.ts, frontend/src/components/DataTable/TableArchivedActionsMenu/TableArchivedActionsMenu.tsx, frontend/src/features/admin/hooks/useUserActions.ts, frontend/src/features/archive/components/ArchivedUsers.tsx, frontend/src/features/archive/containers/ArchivePage.tsx, frontend/src/features/archive/hooks/useArchivedUsersActions.ts, frontend/src/store/slices/userSlice.ts, frontend/src/store/thunks/userThunk.ts
[JE2-248](https://botsmannatashaa.atlassian.net/browse/JE2-248)
=> JE2-248 Created table for archived users

frontend/src/components/CustomSelect/CustomSelect.tsx, frontend/src/components/ui/textarea.tsx, frontend/src/features/services/components/ServiceForm.tsx, frontend/src/features/services/hooks/useServiceForm.ts, frontend/src/features/tasks/components/TaskBoard.tsx, frontend/src/features/tasks/components/TaskForm.tsx, frontend/src/features/tasks/hooks/useTaskForm.ts
https://botsmannatashaa.atlassian.net/browse/JE2-223
=> [JE2-223] Updated TaskForm styles

api/src/dto/update-user.dto.ts, api/src/services/user.service.ts, frontend/src/components/AppToolbar/UserMenu.tsx, frontend/src/features/admin/components/UsersDataList.tsx, frontend/src/features/admin/containers/UserPage.tsx, frontend/src/features/users/components/RegistrationForm.tsx, frontend/src/features/users/hooks/useRegistrationForm.ts, frontend/src/store/slices/authSlice.ts, frontend/src/store/slices/userSlice.ts, frontend/src/store/thunks/userThunk.ts, frontend/src/types.d.ts
https://botsmannatashaa.atlassian.net/browse/JE2-264
=> JE2-264. Implemented user editing functionality

frontend/src/app/store.ts, frontend/src/store/slices/invoiceSlice.ts, frontend/src/store/thunks/invoiceThunk.ts, frontend/src/types.d.ts
https://botsmannatashaa.atlassian.net/browse/JE2-242
=> Je2 242 Create Slice and Thunk for invoices

api/src/services/user.service.ts, frontend/src/features/users/containers/LoginPage.tsx
https://botsmannatashaa.atlassian.net/browse/JE2-249
=> JE2-249. Prevented login for archived users

api/src/seeder/seeder.service.ts, frontend/src/features/admin/containers/AdminPage.tsx, frontend/src/features/invoices/components/InvoicesDataList.tsx, frontend/src/features/invoices/hooks/useInvoicesList.ts
https://botsmannatashaa.atlassian.net/browse/JE2-245
=> JE2-245. Created Invoice Data List and hook for it

frontend/src/features/admin/containers/AdminPage.tsx, frontend/src/features/invoices/containers/InvoicesPage.tsx, frontend/src/features/invoices/hooks/useInvoicesPage.ts, frontend/src/features/services/containers/ServicesPage.tsx
https://botsmannatashaa.atlassian.net/browse/JE2-244
=> [JE2-244] Add InvoicesPage.tsx

frontend/src/features/admin/components/UsersDataList.tsx, frontend/src/features/invoices/components/InvoicesDataList.tsx
https://botsmannatashaa.atlassian.net/browse/JE2-266
=> JE2-266. Bug fix for Invoice number column hiding

frontend/src/components/ProtectedElement/ProtectedElement.tsx
[JE2-239](https://botsmannatashaa.atlassian.net/browse/JE2-239)
=> JE2-239 Created component to hide items depending on the role of the user

frontend/src/utils/axiosAPI.ts, frontend/src/utils/sanitizeData.ts
https://botsmannatashaa.atlassian.net/browse/JE2-190
=> [JE2-190] Added protection against xss attacks

frontend/src/App.tsx, frontend/src/components/AllowedRoute/AllowedRoute.tsx, frontend/src/components/DataTable/TableActionsMenu/TableActionsMenu.tsx, frontend/src/components/DataTable/TableArchivedActionsMenu/TableArchivedActionsMenu.tsx, frontend/src/components/SidebarContent/SidebarContent.tsx, frontend/src/features/admin/containers/UserPage.tsx, frontend/src/features/arrivals/containers/ArrivalDetails.tsx, frontend/src/features/arrivals/containers/ArrivalPage.tsx, frontend/src/features/clients/containers/ClientDetail.tsx, frontend/src/features/clients/containers/ClientPage.tsx, frontend/src/features/counterparties/containers/CounterpartiesPage.tsx, frontend/src/features/invoices/containers/InvoicesPage.tsx, frontend/src/features/orders/containers/OrderDetails.tsx, frontend/src/features/orders/containers/OrderPage.tsx, frontend/src/features/products/containers/ProductDetails.tsx, frontend/src/features/products/containers/ProductPage.tsx, frontend/src/features/services/containers/ServicesPage.tsx, frontend/src/features/stocks/containers/StockDetails.tsx, frontend/src/features/stocks/containers/StockPage.tsx, frontend/src/features/tasks/components/TaskBoard.tsx, frontend/src/features/tasks/components/TaskCard.tsx
[JE2-163](https://botsmannatashaa.atlassian.net/browse/JE2-163)
Also done tocket: [JE2-253](https://botsmannatashaa.atlassian.net/browse/JE2-253)
=> JE2-163 Restrict access by user roles

api/src/controllers/invoices.controller.ts, api/src/controllers/services.controller.ts, api/src/services/invoices.service.ts, api/src/services/services.service.ts, frontend/src/features/archive/components/ArchivedInvoices.tsx, frontend/src/features/archive/components/ArchivedServices.tsx, frontend/src/features/archive/containers/ArchivePage.tsx, frontend/src/features/archive/hooks/useArchivedInvoiceActions.ts, frontend/src/features/archive/hooks/useArchivedServicesActions.ts, frontend/src/store/slices/invoiceSlice.ts, frontend/src/store/slices/serviceSlice.ts, frontend/src/store/thunks/serviceThunk.ts
https://botsmannatashaa.atlassian.net/browse/JE2-271
=> [JE2-271] Added tabs invoices and services in archive

api/src/dto/create-arrival.dto.ts, api/src/schemas/arrival.schema.ts, frontend/src/components/CustomSelect/CustomSelect.tsx, frontend/src/components/ui/textarea.tsx, frontend/src/features/arrivals/components/ArrivalForm.tsx, frontend/src/features/arrivals/hooks/useArrivalForm.ts, frontend/src/features/arrivals/state/arrivalState.ts, frontend/src/features/tasks/components/TaskForm.tsx, frontend/src/features/tasks/hooks/useTaskForm.ts, frontend/src/types.d.ts
https://botsmannatashaa.atlassian.net/browse/JE2-279
=> [JE2-279] Fixed CustomSelect onBlur bug

frontend/src/components/Buttons/BackButton.tsx
https://botsmannatashaa.atlassian.net/browse/JE2-269
Updated Back button functionality on tab pages to navigate without considering history.
=> JE2-269 Updated Back button functionality 

frontend/src/constants.ts, frontend/src/utils/sanitizeData.ts
=> JE2-280 sanitization fixed

frontend/src/features/stocks/hooks/useWriteOffForm.ts, frontend/src/store/slices/stocksSlice.ts
=> JE2-284 bugfix for ticket JE2-197: loading spinner upon form submission

api/src/services/stocks.service.ts, api/test/stocks.service.spec.ts
https://botsmannatashaa.atlassian.net/browse/JE2-281
=> Je2 281  Сhanged the logic of deleting and archiving the warehouse

api/src/seeder/seeder.service.ts, api/src/services/report.service.ts, api/src/types.d.ts, api/test/report.service.spec.ts, frontend/src/features/reports/clientReport/components/ClientReport.tsx, frontend/src/features/reports/clientReport/components/ClientReportDataList.tsx, frontend/src/features/reports/clientReport/components/clientInvoicesBarChart.tsx, frontend/src/features/reports/containers/ReportPage.tsx, frontend/src/features/reports/taskPeport/components/TaskReportDataList.tsx, frontend/src/features/reports/utils/TypesProps.ts, frontend/src/types.d.ts
https://botsmannatashaa.atlassian.net/browse/JE2-295
=> Je2 295 Added information on arrivals and invoices to the customer report

frontend/src/features/clients/components/ClientForm.tsx, frontend/src/features/clients/hooks/useClientForm.ts
[JE2-296](https://botsmannatashaa.atlassian.net/browse/JE2-296)
=> JE2-296 Added additional onBlur validation in Client form

frontend/src/components/ItemsList/ItemsList.tsx, frontend/src/components/Tables/ProductsTable.tsx, frontend/src/components/ui/accordion.tsx, frontend/src/features/clients/components/ClientDetails.tsx, frontend/src/features/clients/components/ClientsDataList.tsx, frontend/src/features/clients/hooks/useClientActions.ts, frontend/src/features/invoices/components/InvoiceForm.tsx, frontend/src/features/products/components/ProductDetails.tsx, frontend/src/features/products/components/ProductsDataList.tsx, frontend/src/features/products/hooks/useProductActions.ts
https://botsmannatashaa.atlassian.net/browse/JE2-301
=> [JE2-301] Added an ability to open Client/ProductDetails modals by id

api/src/services/clients.service.ts, api/test/client.service.spec.ts, frontend/src/features/stocks/components/StockProductsDataList.tsx
https://botsmannatashaa.atlassian.net/browse/JE2-278
https://botsmannatashaa.atlassian.net/browse/JE2-285
=> Je2 278 Added processing of negative values ​​on the warehouse detail page, changed the logic of archiving and deleting clients

frontend/src/features/arrivals/components/ArrivalForm.tsx, frontend/src/features/arrivals/containers/ArrivalDetails.tsx, frontend/src/features/arrivals/hooks/useArrivalForm.ts, frontend/src/features/orders/components/OrderForm.tsx, frontend/src/features/orders/containers/OrderDetails.tsx, frontend/src/features/orders/hooks/useOrderForm.ts
https://botsmannatashaa.atlassian.net/browse/JE2-261
=> [JE2-261] Fix bag in arrival and order form

frontend/src/features/invoices/containers/InvoiceDetails.tsx, frontend/src/features/invoices/hooks/useInvoiceDetails.ts, frontend/src/features/invoices/hooks/useInvoiceForm.ts, frontend/src/features/invoices/state/invoiceState.ts, frontend/src/features/invoices/types/invoiceTypes.ts
https://botsmannatashaa.atlassian.net/browse/JE2-302
=> JE2-302. Invoice hook type bug fix, fixed excel service type display

frontend/src/components/Tables/InvoiceServicesTable.tsx, frontend/src/components/Tables/ServicesTable.tsx, frontend/src/features/invoices/components/InvoicesDataList.tsx, frontend/src/features/invoices/containers/InvoiceDetails.tsx, frontend/src/features/invoices/hooks/useInvoiceDetails.ts, frontend/src/features/reports/clientReport/components/clientInvoicesBarChart.tsx, frontend/src/features/services/components/ServicesDataList.tsx, frontend/src/features/stocks/components/StockDefectsDataList.tsx, frontend/src/utils/formatMoney.ts
https://botsmannatashaa.atlassian.net/browse/JE2-290
=> JE2-290. Added decimals display to every money number

frontend/src/components/Tables/ServicesTable.tsx, frontend/src/features/invoices/components/InvoiceForm.tsx, frontend/src/features/services/components/ServiceDetails.tsx
https://botsmannatashaa.atlassian.net/browse/JE2-318
=> JE2-318. Additional decimals and currency display

frontend/src/features/tasks/components/TaskDetails.tsx
https://botsmannatashaa.atlassian.net/browse/JE2-317
Fixed Task details width
=> JE2-317 Fixed Task details width

frontend/src/features/stocks/hooks/useStockForm.ts, frontend/src/types.d.ts
https://botsmannatashaa.atlassian.net/browse/JE2-319
Fixed stock update
=> JE2-319 Fixed stock update

frontend/src/index.css
https://botsmannatashaa.atlassian.net/browse/JE2-321
=> [JE2-321] Fix bag onClick PieChart

api/src/services/services.service.ts
https://botsmannatashaa.atlassian.net/browse/JE2-322
=> Je2 322 Add verification services during archiving and deletion

frontend/src/components/ui/dialog.tsx
https://botsmannatashaa.atlassian.net/browse/JE2-323
=> [JE2-323] Add cursor-pointer in close Modal

api/src/controllers/tasks.controller.ts, api/src/dto/create-task.dto.ts, frontend/src/components/LogsAccordionView/LogsAccordionView.tsx, frontend/src/features/tasks/components/TaskDetails.tsx, frontend/src/features/tasks/hooks/onDragEnd.ts
https://botsmannatashaa.atlassian.net/browse/JE2-320
Fixed task status change on the details page for stock workers.
Fixed task drag-and-drop behavior.
Fixed task details view on mobiles.
=> JE2-320 Fixed task status change on the details page for stock workers.

frontend/src/App.tsx, frontend/src/components/SidebarContent/SidebarContent.tsx, frontend/src/features/products/components/ProductDetails.tsx
https://botsmannatashaa.atlassian.net/browse/JE2-310
=> [JE2-310] Updated stock-worker role access to products page

frontend/src/components/CopyText/CopyText.tsx
https://botsmannatashaa.atlassian.net/browse/JE2-324
=> [JE2-324] Fixed the tooltip displaying

frontend/src/features/tasks/components/UserList.tsx
https://botsmannatashaa.atlassian.net/browse/JE2-333
=> [JE2-333] Fixed the bug in the UserList by deleting ScrollArea

frontend/src/features/appUsage/containers/AppUsage.tsx, frontend/src/features/arrivals/containers/ArrivalDetails.tsx, frontend/src/features/orders/containers/OrderDetails.tsx, frontend/src/features/users/containers/LoginPage.tsx
https://botsmannatashaa.atlassian.net/browse/JE2-336
=> [JE2-336] Manager redirect bug fix

frontend/src/features/arrivals/containers/ArrivalDetails.tsx, frontend/src/features/arrivals/hooks/useArrivalDetails.ts, frontend/src/features/orders/containers/OrderDetails.tsx, frontend/src/features/orders/hooks/useOrderDetails.ts, frontend/src/index.css, frontend/src/utils/getOS.ts
https://botsmannatashaa.atlassian.net/browse/JE2-338
=> [JE2-338] Fixed TabsList styles
